# Generated by Django 4.1.7 on 2023-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "admin_username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("admin_password", models.TextField()),
                ("admin_name", models.TextField()),
                ("admin_address", models.TextField()),
            ],
            options={"db_table": "Admin",},
        ),
        migrations.CreateModel(
            name="Admitted",
            fields=[
                ("admission_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.IntegerField()),
                ("room_id", models.IntegerField()),
                ("currently_admitted", models.BooleanField()),
            ],
            options={"db_table": "Admitted",},
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.IntegerField()),
                ("doctor_username", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("symptoms", models.CharField(max_length=200)),
                ("completed", models.BooleanField()),
            ],
            options={"db_table": "Appointment",},
        ),
        migrations.CreateModel(
            name="Data_Entry_Operator",
            fields=[
                (
                    "deo_username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("deo_password", models.TextField()),
                ("deo_name", models.TextField()),
                ("deo_address", models.TextField()),
            ],
            options={"db_table": "Data_Entry_Operator",},
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "doctor_username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("doctor_password", models.TextField()),
                ("doctor_name", models.TextField()),
                ("doctor_address", models.TextField()),
                ("department", models.TextField()),
            ],
            options={"db_table": "Doctor",},
        ),
        migrations.CreateModel(
            name="Front_Desk_Operator",
            fields=[
                (
                    "fdo_username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("fdo_password", models.TextField()),
                ("fdo_name", models.TextField()),
                ("fdo_address", models.TextField()),
            ],
            options={"db_table": "Front_Desk_Operator",},
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_name", models.TextField()),
                ("patient_address", models.TextField()),
                ("admitted", models.BooleanField()),
            ],
            options={"db_table": "Patient",},
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("availability", models.BooleanField()),
            ],
            options={"db_table": "Room",},
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.IntegerField()),
                ("doctor_username", models.CharField(max_length=100)),
                ("procedure_name", models.CharField(max_length=100, null=True)),
                ("appointment_id", models.IntegerField()),
                ("saved_test", models.BooleanField()),
                ("date", models.DateField(null=True)),
            ],
            options={"db_table": "Test",},
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                ("treatment_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.IntegerField()),
                ("doctor_username", models.CharField(max_length=100)),
                ("prescription", models.CharField(max_length=200, null=True)),
                ("appointment_id", models.IntegerField()),
                ("saved_treatment", models.BooleanField()),
                ("date", models.DateField(null=True)),
            ],
            options={"db_table": "Treatment",},
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("patient_id", "doctor_username", "date"), name="appointment_pk"
            ),
        ),
    ]
