# Generated by Django 4.1.7 on 2023-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('admin_password', models.TextField()),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Admitted',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Data_Entry_Operator',
            fields=[
                ('deo_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('deo_password', models.TextField()),
                ('deo_name', models.TextField()),
                ('deo_address', models.TextField()),
                ('tests_scheduled', models.IntegerField()),
                ('treatments_scheduled', models.IntegerField()),
            ],
            options={
                'db_table': 'Data_Entry_Operator',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doctor_password', models.TextField()),
                ('doctor_name', models.TextField()),
                ('doctor_address', models.TextField()),
                ('department', models.TextField()),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Front_Desk_Operator',
            fields=[
                ('fdo_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fdo_password', models.TextField()),
                ('fdo_name', models.TextField()),
                ('fdo_address', models.TextField()),
                ('registered_num', models.IntegerField()),
                ('admitted_num', models.IntegerField()),
                ('discharged_num', models.IntegerField()),
            ],
            options={
                'db_table': 'Front_Desk_Operator',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.TextField()),
                ('patient_address', models.TextField()),
                ('admitted', models.BooleanField()),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.TextField()),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'Procedure',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('availability', models.BooleanField()),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('procedure_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Treatment',
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient_id', 'doctor_id', 'date'), name='appointment_pk'),
        ),
    ]
